# Generated by Django 5.2 on 2025-07-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='passing_score',
            field=models.PositiveIntegerField(default=80, help_text='Minimum score (in %) required to pass this assessment.'),
        ),
    ]
