# Generated by Django 5.2 on 2025-07-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_passing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='allow_retake',
            field=models.BooleanField(default=False, help_text='Allow employees to retake this assessment.'),
        ),
    ]
