# Generated by Django 5.2 on 2025-07-10 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_allow_retake'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (optional). Leave blank for no time limit.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
