# Generated by Django 5.2 on 2025-07-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessment_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='max_retakes',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of retakes allowed (leave blank for unlimited).', null=True),
        ),
    ]
