# Generated by Django 5.2 on 2025-07-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessment_max_retakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
