# Generated by Django 5.2 on 2025-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assessment_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
